import json

datastring = '''{
    "parameters": {
        "DayOffset": "0",
        "GameDate": "10/27/2015",
        "LeagueID": "00"
    },
    "resource": "scoreboardV2",
    "resultSets": [
        {
            "headers": [
                "GAME_DATE_EST",
                "GAME_SEQUENCE",
                "GAME_ID",
                "GAME_STATUS_ID",
                "GAME_STATUS_TEXT",
                "GAMECODE",
                "HOME_TEAM_ID",
                "VISITOR_TEAM_ID",
                "SEASON",
                "LIVE_PERIOD",
                "LIVE_PC_TIME",
                "NATL_TV_BROADCASTER_ABBREVIATION",
                "LIVE_PERIOD_TIME_BCAST",
                "WH_STATUS"
            ],
            "name": "GameHeader",
            "rowSet": [
                [
                    "2015-10-27T00:00:00",
                    1,
                    "0021500001",
                    1,
                    "8:00 pm ET",
                    "20151027/DETATL",
                    1610612737,
                    1610612765,
                    "2015",
                    0,
                    "     ",
                    null,
                    "Q0       - ",
                    0
                ],
                [
                    "2015-10-27T00:00:00",
                    2,
                    "0021500002",
                    1,
                    "8:00 pm ET",
                    "20151027/CLECHI",
                    1610612741,
                    1610612739,
                    "2015",
                    0,
                    "     ",
                    "TNT",
                    "Q0       - TNT",
                    0
                ],
                [
                    "2015-10-27T00:00:00",
                    3,
                    "0021500003",
                    1,
                    "10:30 pm ET",
                    "20151027/NOPGSW",
                    1610612744,
                    1610612740,
                    "2015",
                    0,
                    "     ",
                    "TNT",
                    "Q0       - TNT",
                    0
                ]
            ]
        },
        {
            "headers": [
                "GAME_DATE_EST",
                "GAME_SEQUENCE",
                "GAME_ID",
                "TEAM_ID",
                "TEAM_ABBREVIATION",
                "TEAM_CITY_NAME",
                "TEAM_WINS_LOSSES",
                "PTS_QTR1",
                "PTS_QTR2",
                "PTS_QTR3",
                "PTS_QTR4",
                "PTS_OT1",
                "PTS_OT2",
                "PTS_OT3",
                "PTS_OT4",
                "PTS_OT5",
                "PTS_OT6",
                "PTS_OT7",
                "PTS_OT8",
                "PTS_OT9",
                "PTS_OT10",
                "PTS",
                "FG_PCT",
                "FT_PCT",
                "FG3_PCT",
                "AST",
                "REB",
                "TOV"
            ],
            "name": "LineScore",
            "rowSet": [
                [
                    "2015-10-27T00:00:00",
                    1,
                    "0021500001",
                    1610612737,
                    "ATL",
                    "Atlanta",
                    "0-0",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2015-10-27T00:00:00",
                    1,
                    "0021500001",
                    1610612765,
                    "DET",
                    "Detroit",
                    "0-0",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2015-10-27T00:00:00",
                    2,
                    "0021500002",
                    1610612741,
                    "CHI",
                    "Chicago",
                    "0-0",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2015-10-27T00:00:00",
                    2,
                    "0021500002",
                    1610612739,
                    "CLE",
                    "Cleveland",
                    "0-0",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2015-10-27T00:00:00",
                    3,
                    "0021500003",
                    1610612744,
                    "GSW",
                    "Golden State",
                    "0-0",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2015-10-27T00:00:00",
                    3,
                    "0021500003",
                    1610612740,
                    "NOP",
                    "New Orleans",
                    "0-0",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ]
            ]
        },
        {
            "headers": [
                "GAME_ID",
                "HOME_TEAM_ID",
                "VISITOR_TEAM_ID",
                "GAME_DATE_EST",
                "HOME_TEAM_WINS",
                "HOME_TEAM_LOSSES",
                "SERIES_LEADER"
            ],
            "name": "SeriesStandings",
            "rowSet": []
        },
        {
            "headers": [
                "GAME_ID",
                "LAST_GAME_ID",
                "LAST_GAME_DATE_EST",
                "LAST_GAME_HOME_TEAM_ID",
                "LAST_GAME_HOME_TEAM_CITY",
                "LAST_GAME_HOME_TEAM_NAME",
                "LAST_GAME_HOME_TEAM_ABBREVIATION",
                "LAST_GAME_HOME_TEAM_POINTS",
                "LAST_GAME_VISITOR_TEAM_ID",
                "LAST_GAME_VISITOR_TEAM_CITY",
                "LAST_GAME_VISITOR_TEAM_NAME",
                "LAST_GAME_VISITOR_TEAM_CITY1",
                "LAST_GAME_VISITOR_TEAM_POINTS"
            ],
            "name": "LastMeeting",
            "rowSet": [
                [
                    "0021500001",
                    "0021401109",
                    "2015-03-31T00:00:00",
                    1610612737,
                    "Atlanta",
                    "Hawks",
                    "ATL",
                    95,
                    1610612765,
                    "Detroit",
                    "Pistons",
                    "DET",
                    105
                ],
                [
                    "0021500002",
                    "0041400216",
                    "2015-05-14T00:00:00",
                    1610612741,
                    "Chicago",
                    "Bulls",
                    "CHI",
                    73,
                    1610612739,
                    "Cleveland",
                    "Cavaliers",
                    "CLE",
                    94
                ],
                [
                    "0021500003",
                    "0041400144",
                    "2015-04-25T00:00:00",
                    1610612744,
                    "Golden State",
                    "Warriors",
                    "GSW",
                    109,
                    1610612740,
                    "New Orleans",
                    "Pelicans",
                    "NOP",
                    98
                ]
            ]
        },
        {
            "headers": [
                "TEAM_ID",
                "LEAGUE_ID",
                "SEASON_ID",
                "STANDINGSDATE",
                "CONFERENCE",
                "TEAM",
                "G",
                "W",
                "L",
                "W_PCT",
                "HOME_RECORD",
                "ROAD_RECORD"
            ],
            "name": "EastConfStandingsByDay",
            "rowSet": [
                [
                    1610612737,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Atlanta",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612738,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Boston",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612751,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Brooklyn",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612766,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Charlotte",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612741,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Chicago",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612739,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Cleveland",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612765,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Detroit",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612754,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Indiana",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612748,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Miami",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612749,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Milwaukee",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612752,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "New York",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612753,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Orlando",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612755,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Philadelphia",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612761,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Toronto",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612764,
                    "00",
                    "22015",
                    "10/27/2015",
                    "East",
                    "Washington",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ]
            ]
        },
        {
            "headers": [
                "TEAM_ID",
                "LEAGUE_ID",
                "SEASON_ID",
                "STANDINGSDATE",
                "CONFERENCE",
                "TEAM",
                "G",
                "W",
                "L",
                "W_PCT",
                "HOME_RECORD",
                "ROAD_RECORD"
            ],
            "name": "WestConfStandingsByDay",
            "rowSet": [
                [
                    1610612742,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "Dallas",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612743,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "Denver",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612744,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "Golden State",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612745,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "Houston",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612746,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "L.A. Clippers",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612747,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "L.A. Lakers",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612763,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "Memphis",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612750,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "Minnesota",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612740,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "New Orleans",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612760,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "Oklahoma City",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612756,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "Phoenix",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612757,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "Portland",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612758,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "Sacramento",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612759,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "San Antonio",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ],
                [
                    1610612762,
                    "00",
                    "22015",
                    "10/27/2015",
                    "West",
                    "Utah",
                    0,
                    0,
                    0,
                    0.0,
                    "0-0",
                    "0-0"
                ]
            ]
        },
        {
            "headers": [
                "GAME_ID",
                "PT_AVAILABLE"
            ],
            "name": "Available",
            "rowSet": [
                [
                    "0021500002",
                    0
                ],
                [
                    "0021500003",
                    0
                ],
                [
                    "0021500001",
                    0
                ]
            ]
        },
        {
            "headers": [
                "GAME_ID",
                "TEAM_ID",
                "TEAM_CITY",
                "TEAM_NICKNAME",
                "TEAM_ABBREVIATION",
                "PTS_PLAYER_ID",
                "PTS_PLAYER_NAME",
                "PTS",
                "REB_PLAYER_ID",
                "REB_PLAYER_NAME",
                "REB",
                "AST_PLAYER_ID",
                "AST_PLAYER_NAME",
                "AST"
            ],
            "name": "TeamLeaders",
            "rowSet": []
        },
        {
            "headers": [
                "GAME_ID",
                "LEAG_TIX"
            ],
            "name": "TicketLinks",
            "rowSet": [
                [
                    "0021500001",
                    "http://www.nba.com/hawks/tickets"
                ],
                [
                    "0021500002",
                    "http://www.nba.com/bulls/tickets"
                ],
                [
                    "0021500003",
                    "http://www.nba.com/warriors/tickets"
                ]
            ]
        },
        {
            "headers": [],
            "name": "WinProbability",
            "rowSet": []
        }
    ]
}'''


response = {}

x = json.loads(datastring)
results = x['resultSets']

for result in results:

    # parse a result set
    headers = result['headers']
    key = result['name']
    rows = result['rowSet']

    # parse the rows
    values = []
    for row in rows:

        data = {}

        index = 0
        for col in row:
            data[headers[index]] = col

            index += 1

        values.append(data)

    response[key] = values

print json.dumps(response)


